### PR TITLE
Added support for continuous integration

### PR DESCRIPTION
**Pull request by Seraph2**
Support for CI on Windows and Linux has now been added. It can also be made possible to create a new release upon creating a git tag.

Apparently the lower-case "license" file has disappeared because Windows has no case-sensitivity on files. Perhaps it would make sense to also have one license file?

### CODE REVIEW

**Comment by FredyH** [comment]
Why did you delete the license?

**Comment by Seraph2** [comment]
It is not intentional, it seems as it happens because I am on Windows. Since Windows files are not case sensitive, it treats the files “license” and “LICENSE” as the same file. If you refer to your branch here you can see there is two license files with the same content but different filename:
https://github.com/FredyH/MySQLOO/tree/x64

I am not sure how to go about making a commit without at least having one of the license files deleted due to Windows.

Perhaps it would make more sense to have one of them deleted? Having a “LICENSE” file seems to be the best.

**Comment by FredyH** [comment]
Ah that makes sense, yeah then we'll just remove that one.

As for the CI, I think it's not building the x86 version under linux right now (not sure about windows) but I think we still need to support x86 for the time being (unfortunately).

**Comment by FredyH** [comment]
If you just run make without specifying config=... it builds the x86 version by default and should place the x86 dll besides the x64 one

**Comment by Seraph2** [comment]
Alright, I will combine x86 and x64 into one on Linux, then run both those make commands.

**Comment by Seraph2** [comment]
There is now support for both x86 and x64. On Windows it is ran as 2 separate configurations (which is the preferred), whereas on Linux it is ran as 1. I feel it is the best to keep it Linux like this for now until OSX support will be added.

**Pull request merged**
